### ISSUE TITLE
CURL error

### ISSUE THREAD

**Issue by jessicalily** [gri3li/php-ethereum-smart-contract#1]
`Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 1000 milliseconds with 0 out of 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in D:\xampp\htdocs\ethsmartphp\php-ethereum-smart-contract-master\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:200 Stack trace: #0 D:\xampp\htdocs\ethsmartphp\php-ethereum-smart-contract-master\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 D:\xampp\htdocs\ethsmartphp\php-ethereum-smart-contract-master\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 D:\xampp\htdocs\ethsmartphp\php-ethereum-smart-contract-master\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handl in D:\xampp\htdocs\ethsmartphp\php-ethereum-smart-contract-master\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 200`

Can anyone tell me what this error is about? 

The Instance Im using 

$instance = EthereumSmartContract::createByHost(
    'https://data-seed-prebsc-1-s1.binance.org:8545',
    '97', // mainnet
    'CONTRACT ADRS', // contract address
    file_get_contents('mycoin.json') // abi string
);

**Comment by romziki** [comment]
try putting a bigger curl timeout, i.e. 5 seconds.

**Comment by JinZhuXing** [comment]
@romziki How can I set it?
Please send me a sample code.
Thank you.

**Comment by gri3li** [comment]
@jessicalily @JinZhuXing  The [EthereumSmartContract::createByHost()](https://github.com/gri3li/php-ethereum-smart-contract/blob/master/src/EthereumSmartContract.php#L80C28-L80C40) function has a 5th parameter to set the timeout.

But the problem with the timeout may be due to problems on the node side, if setting the timeout does not help, you need to try using another node
